#! /bin/sh
BASEDIR=$(dirname "$(readlink -f "$0")")

die() {
    echo
    echo "$@"
    exit 1
}

git pull

[ -f "$BASEDIR/.env" ] || die "Missing .env"

sudo docker compose pull && sudo docker compose up -d
